### ISSUE TITLE
Customize the JSON

### ISSUE THREAD

**Issue by yfried** [Eernie/bitbucket-webhooks-plugin#79]
Hi,
This plugin seems great, but could you please allow users to create their own JSON data, based given variables (based on variables described in the current documented JSON)?
That way we can use this plugin to communicate with services other than Jenkins.

**Comment by casz** [comment]
What data do you require?

**Comment by maveric1977** [comment]
Hi, Sorry for jumping in, but I do have the same requirement.
In my case, I want to be able to trigger a CodeReview creation in Upsource based on PR creation event.
Upsource API requires a `POST` request to be made with the following body:

Field | Type | Label | Description
-- | -- | -- | --
projectId | string | required | Project ID in Upsource
title | string | optional | Review title (unused, left for compatibility with older clients)
revisions | string | repeated | Revisions to attach
branch | string | optional | Branch name

**Comment by casz** [comment]
seems to go beyond the usage of this plugin, now you want to have the plugin store a project id for Upsource. You are free to fork the repo, modify it to your needs when forking I suggest you change the application id and pretty much change the existing functionality to support Upsource specific event listeners.

**Comment by maveric1977** [comment]
Sure thing. Although IMHO being able to provide the body of the `POST` request is out of the scope of a `Webhook` plugin which is supposed to send `POST` requests to other servers.

**Comment by casz** [comment]
Well I am not willing to maintain or develop such a feature. :relieved:

**Comment by casz** [comment]
@yfried closing since you never answered

**Comment by abishek3876** [comment]
I think this issue should be left open. Anyone wishing to implement this can contribute in the future. This is a very good feature to have IMO.

**Comment by casz** [comment]
well will that person be willing to become a co-maintainer then?

**Comment by Eernie** [comment]
As the owner of this repo I close this issue because I don't see any benefit for this feature. When the person things they need it, they can either create the feature and make a PR or find an other plugin to request this from. 

The reason I don't want this in this plugin is because this has nothing to do with the at the time missing post webhooks functionality. This plugin was build so we could share standard information just like the cloud solution does. Having "custom" json is way more complex then anyone should want from a post webhook plugin. If you miss some information in the payload you should just add it to the plugin instead of needing variables and custom json objects.
